### ISSUE TITLE
Update DexScrenner

### ISSUE THREAD

**Issue by Cryptobertl** [New-Project-Zero/new-project-zero.github.io#1]
The community proposes to update the dex with following banner ![image](https://github.com/user-attachments/assets/b81f984b-284c-49ce-804e-7a0927d51a8c) as well as the telegram link on dexscreener with https://t.me/New_Project_Zero the twitter link https://x.com/project0ver?s=21 as well as the homepage to https://new-project-zero.github.io/

The dex will be paid by a community member without costs to the dev if he is committed to stay on development.

Please to agree and sent an official ok to the group telegram also to start the process

**Comment by doctorLightning** [comment]
will be attended to 🌱

**Comment by doctorLightning** [comment]
dex is active🌱
