### ISSUE TITLE
Wallet connectivity

### ISSUE THREAD

**Issue by jezisawesome** [New-Project-Zero/new-project-zero.github.io#3]
Wallet connect (Phantom/Desktop (MacOS)) on https://new-project-zero.github.io/ shows zero token balance

**Comment by Vickynicole** [comment]
Hello @jezisawesome 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WAL07638
Please see the link below to our dedicated support line:
[Wallet DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by doctorLightning** [comment]
fixed and updated 🌱
